apiVersion: osac.openshift.io/v1alpha1
kind: Host
metadata:
  name: host-54321
  namespace: osac-namespace
  ownerReferences:
  - apiVersion: osac.openshift.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: BareMetalPool
    name: baremetalpool-sample
    uid: fe993592-b98d-4e91-b36a-b0196d32d237
spec:
  matches:
    hostClass: fc430
    managedBy: None
    provisionState: available
  setUpWorkflow:
    workflowID: host-image-provision
    input:
      imageURL: http://image.iso
      network: private-network-id
  tearDownWorkflow:
    workflowID: host-unprovision
  online: true
  networkInterfaces:
    - macAddress: aa:bb:cc:dd:ee:f1
      network: private-vlan-network
  provisioning:
    state: available
status:
  setUpWorkflowOutput:
    example: some-value
  id: 519d6b37-13a9-444c-9a2a-bcac8a33dc44
  name: host-name
  hostManagementClass: openstack
  networkClass: openstack
  poweredOn: false
  networkInterfaces:
    - macAddress: aa:bb:cc:dd:ee:f1
    - macAddress: aa:bb:cc:dd:ee:f2
